node {

    //定义mvn环境
    def mvnHome = tool 'M3'
    env.PATH = "${mvnHome}/bin:${env.PATH}"

    stage('build') {

        // 打包源码
        checkout scm
        sh 'mvn -B -DskipTests clean package'

    }

    stage('docker build') {

        //删除镜像
        sh 'chmod +x ./server-config/build/delete.sh'
        sh './server-config/build/delete.sh'
        //构建镜像
        def customImage = docker.build("server-config:latest","./server-config")

    }

    stage("deploy") {

        // 项目部署
        sh 'chmod +x ./server-config/build/deploy.sh'
        sh './server-config/build/deploy.sh'

    }
}