server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://1.15.123.16:8761/eureka
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息间隔时间 (默认为30秒)
  instance:
    lease-expiration-duration-in-seconds: 60  # 注册中心超过这个时间没收到心跳，会视为无效节点(默认为90秒)
    lease-renewal-interval-in-seconds: 30  # 发送心跳间隔时间（默认30秒）
    preferIpAddress: true
    #instanceId: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${eureka.instance.hostname}:${server.port}
    hostname: 1.15.123.16

#  rabbitmq:
#    host: 1.15.123.16
#    port: 5672
#    username: admin
#    password: admin

management:
  endpoints:
    web:
      exposure:
        include: refresh    #手动刷新    http://localhost:8889/actuator/refresh    自动刷新配置: 把手动刷新的地址配置到webhook上
  endpoint:
    health:
      show-details: always