pipeline {
    agent any
    stages {
        stage('check') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                //git 'https://github.com/originalblackhole/spring-cloud-demo.git'
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('build'){
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir 'server-config/build'
                }
            }
            steps {
                sh ' ./build/build.sh'
            }
        }

        stage('deploy'){
            steps {
                sh ' ./build/docker.sh'
            }
        }
    }
}